# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "615bd3fce067badfcf109af3580406d6"
name = "wishlist"
handle = "wishlist-456"
application_url = "https://sacrifice-dean-ahead-burden.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "davidcito.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sacrifice-dean-ahead-burden.trycloudflare.com/auth/callback",
  "https://sacrifice-dean-ahead-burden.trycloudflare.com/auth/shopify/callback",
  "https://sacrifice-dean-ahead-burden.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
